export enum SagaEventType {
  OS_CREATED = 'OS_CREATED',
  BUDGET_GENERATED = 'BUDGET_GENERATED',
  BUDGET_APPROVAL_DECIDED = 'BUDGET_APPROVAL_DECIDED',
  EXECUTION_REQUESTED = 'EXECUTION_REQUESTED',
  EXECUTION_COMPLETED = 'EXECUTION_COMPLETED',
  EXECUTION_FAILED = 'EXECUTION_FAILED',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  ADDITIONAL_REQUESTED = 'ADDITIONAL_REQUESTED',
}

export interface SagaEvent<TPayload = Record<string, unknown>> {
  eventType: SagaEventType;
  workOrderId: number;
  payload: TPayload;
  occurredAt: string;
}
