apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
  namespace: oficina
data:
  PORT: "3000"
  AWS_REGION: "us-east-1"
  SAGA_SNS_TOPIC_ARN: ""
  SAGA_SQS_QUEUE_URL: ""
  MP_WEBHOOK_URL: "https://<host>/billing/webhook/mercadopago"
