apiVersion: v1
kind: Secret
metadata:
  name: billing-secret
  namespace: oficina
type: Opaque
stringData:
  DATABASE_URL: "postgresql://usuario:senha@host:5432/billing_service"
  MP_ACCESS_TOKEN: "TEST-xxxxxxxx-xxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxx"
